apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: flink-poc
spec:
  image: flink_poc:latest
  imagePullPolicy: Never
  flinkVersion: v1_15
  mode: standalone
  flinkConfiguration:
    taskmanager.numberOfTaskSlots: "2"
    kubernetes.entry.path: "/bin/flink-poc.sh"
  serviceAccount: flink
  jobManager:
    resource:
      memory: "2048m"
      cpu: 1
  taskManager:
    resource:
      memory: "2048m"
      cpu: 1
  job:
    jarURI: local:///opt/flink/app/flink-app.jar
    parallelism: 2
    upgradeMode: stateless
